# Firebase Configuration
# You need to replace these values with your actual Firebase project credentials
# Get these from your Firebase Console -> Project Settings -> Service Accounts -> Generate new private key

[firebase]
type = "service_account"
project_id = "lns-poll"
private_key_id = "7a80c328a75b3669e843fcc9e2c84fa6976c308d"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDZSLFvqXNHjRO\ncvM72nXKbMRNs6dN30A+U71iMO8qJP5SRGaPQjSeiDO4YRdd23rcOl1DQf/sqOx7\nzqNHGnl9TbOiDB1qzwgM1R4eM7maxBEKiIjCzuRIVoEWEinNIaYgXM16zXQd2Zd7\nrig1lSaFpCfvSCEt/g92cOksEFtaLP5QGq826MO/mfs/oo1vO7lY0LglFoKwu3FX\nSnXF32VOBhMdSUAj3T/KykE8+eoX2dDL+L3NimJKtVaPMuttpoPU37qCdgtviOv6\nurR6v4Dq1xbcrDgsEXyiuPtgTKFJbiOVjKib/kQDqCdS3LIvYQUN358aPRWw7Ixu\nvhg5f9ThAgMBAAECggEAXVJ/ghylSctkRhemzm5vlcfPFiF5BbtcDqimKjCe+e0D\nPr2GkmOXiCQbN7O/mkdKbca+ZnIuTpT7pcIyv7IIVm13Hy1UG4BYIvDi2p/vxNhi\nHzrIvupbo6UVMDpqlpu8oXZReZaJH/yd2id68uSSqn+VxzYXCsVuEy6oXzBMwUso\nTD6oTDEQXdz7JhJjQlS1EIs1/SRQ7OHmLLvEsW68a2ua50zkER4/WDMkzhef92Io\naUuBBymEax1xjJs5eb0KSkTC0VupcZscc8Ari0YiBU+ZBFA0OGZVF0VjAzoEtqqq\nFptaq9qhUKnwCP7SaJwZ3gzc7lm3v6FdcdzV7wYMZQKBgQDmQkrs004Awfizan/I\nVxcyXF1NRJQ4uGMKmtOEiaRDr4cy6O0g2TUwvPV4C0960ioWbHG3UC9o5u/E1Dd7\nhVDsXcfbudwlwbGvROn5Tb8kTX+GaxFjVV4VyIJaq8gzWmPJ+s1k8AOd+0h+ePbC\nLj07D+d5zyZDzpWBZvMCFdnROwKBgQDZPRWkOCHNkxNfaUNgH3qtkBLCAFRfmdvZ\nIDZA/eoQ07ryAp50zrsgrOTQ55BLkoQDygnp8utGCO6+S6PNXYWkGURvXWZO0D5r\nJlUI6QXppMeRdWoMr42g9O/0JZyIS87LigB2WFNLrCx0m0JR/UZ6nfRCzu6QUCMy\nr9Z5C3sQkwKBgB7tuqiy/WBGrcRTwtRDNn9yPqoZUxuHUO5ku5Kq9mCNHEjvVqK5\n6lYgm4xDYKqrvjGC4YdxAt1BX+V9Z/J0htkpA6Z1Aagkq1xSkmcFVW5n5oBEs3I3\nTkr4wuGw/1Q+iPbhdGNhherbjPJIB0Uv9tOPIFWRSJ+FCTn3fR7Dlp1vAoGAc2gA\nFz26t3tqz0UchfQzOAFR9b43FJKoOLDkIaLCti3FIsxBYcxxnOo8pL5f6cXsXBb5\nLU/frVURgAau/mqwlHzX3lHACB6ZClNS2Wjxuy3O13eI3zRkCR4WW52fisi7E2Y8\n2KITnh/Zfhj9IpFq37kKCnPkSMZJ7KN9TNDMkAECgYBCwWf6HRUnqXm9HaDoRlHe\nbDd7z3QcjT2c/hNuXpVBonp+FtrffhOKLcqA7oPMzZT6NK/G29uza7UQt7PNLCGs\n+QkhpiY03y8HtcBVBqtsNKTdnwbUkFmbI7DM5X64nfvm58zZKS/Dg9ujenfHw4Lr\nJ2P+GEFfOGfAwtigaEkjRA==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@lns-poll.iam.gserviceaccount.com"
client_id = "113877605625612865572"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40lns-poll.iam.gserviceaccount.com"

# Google Sheets Configuration (existing - keep if you want Google Sheets as fallback)
[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project-id.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project-id.iam.gserviceaccount.com"

[google_sheets]
spreadsheet_id = "your-google-sheets-id"